#!/bin/sh
# PROVIDE: netinfo_receiver
# REQUIRE: DAEMON NETWORKING

. /etc/rc.subr
name=netinfo_receiver
rcvar=${name}_enable
command="/usr/local/bin/netinfo"
pidfile="/var/run/${name}.pid"
start_cmd="${name}_start"

# env
N_LISTEN="localhost:1996"

netinfo_receiver_start() {
  echo "Starting ${name}."
  export GIN_MODE=release
  /usr/sbin/daemon -cf -p ${pidfile} ${command} receive -listen=${N_LISTEN}
}

load_rc_config $name
run_rc_command "$1"
