#!/bin/sh
# PROVIDE: netinfo_nconnect
# REQUIRE: DAEMON NETWORKING

. /etc/rc.subr
name=netinfo_nconnect
rcvar=${name}_enable
command="/usr/local/bin/netinfo"
pidfile="/var/run/${name}.pid"
start_cmd="${name}_start"

# env
N_ID="xxx"
N_ENDPOINT="xxx"
N_INTERVAL="5m"

netinfo_nconnect_start() {
  echo "Starting ${name}."
  export GIN_MODE=release
  /usr/sbin/daemon -cf -p ${pidfile} ${command} send nconnect -id=${N_ID} -endpoint=${N_ENDPOINT} -allow_insecure -interval=${N_INTERVAL}
}

load_rc_config $name
run_rc_command "$1"
