#!/bin/sh /etc/rc.common
# https://openwrt.org/docs/guide-developer/procd-init-scripts

USE_PROCD=1
START=90
COMMAND="/usr/bin/netinfo"
N_ID="xxx"
N_ENDPOINT="xxx"
N_INTERVAL="5m"

boot() {
  ubus -t 30 wait_for network.interface network.wireless 2>/dev/null
  rc_procd start_service
}

start_service() {
  procd_open_instance
  procd_set_param command ${COMMAND} send nconnect -id=${N_ID} -endpoint=${N_ENDPOINT} -allow_insecure -interval=${N_INTERVAL}
  procd_set_param pidfile /var/run/netinfo_nconnect.pid
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}