#!/bin/sh /etc/rc.common
# https://openwrt.org/docs/guide-developer/procd-init-scripts

USE_PROCD=1
START=90
COMMAND="/usr/bin/netinfo"
N_ENDPOINT="xxx"
N_ACCESS_KEY_ID="xxx"
N_SECRET_ACCESS_KEY="xxx"
N_BUCKET="xxx"
N_OBJECT_PATH="xxx"
N_ENCRYPTION_KEY="xxx"
N_INTERVAL="5m"

boot() {
  ubus -t 30 wait_for network.interface network.wireless 2>/dev/null
  rc_procd start_service
}

start_service() {
  procd_open_instance
  procd_set_param command ${COMMAND} send s3 -endpoint=${N_ENDPOINT} -path_style -access_key_id=${N_ACCESS_KEY_ID} -secret_access_key=${N_SECRET_ACCESS_KEY} -bucket=${N_BUCKET} -object_path=${N_OBJECT_PATH} -encryption_key=${N_ENCRYPTION_KEY} -interval=${N_INTERVAL}
  procd_set_param pidfile /var/run/wgwd_s3.pid
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}