#!/bin/sh /etc/rc.common

START=90
STOP=01
USE_PROCD=1

N_ID="xxx"
N_ENDPOINT="xxx"
N_INTERVAL="5m"

service_data() {
    echo "netinfo is starting up..."
}

start_service() {
    procd_open_instance
    procd_set_param command /usr/local/bin/netinfo
    procd_append_param command send nconnect -id=${N_ID} -endpoint=${N_ENDPOINT} -allow_insecure -interval=${N_INTERVAL}
    procd_set_param pidfile /var/run/netinfo.pid
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
