#!/bin/sh /etc/rc.common
# https://openwrt.org/docs/guide-developer/procd-init-scripts

USE_PROCD=1
START=90
COMMAND="/usr/bin/netinfo"
N_ENDPOINT="xxx"
N_USERNAME="xxx"
N_PASSWORD="xxx"
N_FILEPATH="xxx"
N_ENCRYPTION_KEY="xxx"
N_INTERVAL="5m"

boot() {
  ubus -t 30 wait_for network.interface network.wireless 2>/dev/null
  rc_procd start_service
}

start_service() {
  procd_open_instance
  procd_set_param command ${COMMAND} send webdav -endpoint=${N_ENDPOINT} -username=${N_USERNAME} -password=${N_PASSWORD} -filepath=${N_FILEPATH} -encryption_key=${N_ENCRYPTION_KEY} -interval=${N_INTERVAL}
  procd_set_param pidfile /var/run/wgwd_webdav.pid
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}