// Code generated by ent, DO NOT EDIT.

package record

import (
	"netinfo/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldUpdatedAt, v))
}

// RequestIP applies equality check predicate on the "requestIP" field. It's identical to RequestIPEQ.
func RequestIP(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldRequestIP, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldUpdatedAt, v))
}

// RequestIPEQ applies the EQ predicate on the "requestIP" field.
func RequestIPEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldRequestIP, v))
}

// RequestIPNEQ applies the NEQ predicate on the "requestIP" field.
func RequestIPNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldRequestIP, v))
}

// RequestIPIn applies the In predicate on the "requestIP" field.
func RequestIPIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldRequestIP, vs...))
}

// RequestIPNotIn applies the NotIn predicate on the "requestIP" field.
func RequestIPNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldRequestIP, vs...))
}

// RequestIPGT applies the GT predicate on the "requestIP" field.
func RequestIPGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldRequestIP, v))
}

// RequestIPGTE applies the GTE predicate on the "requestIP" field.
func RequestIPGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldRequestIP, v))
}

// RequestIPLT applies the LT predicate on the "requestIP" field.
func RequestIPLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldRequestIP, v))
}

// RequestIPLTE applies the LTE predicate on the "requestIP" field.
func RequestIPLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldRequestIP, v))
}

// RequestIPContains applies the Contains predicate on the "requestIP" field.
func RequestIPContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldRequestIP, v))
}

// RequestIPHasPrefix applies the HasPrefix predicate on the "requestIP" field.
func RequestIPHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldRequestIP, v))
}

// RequestIPHasSuffix applies the HasSuffix predicate on the "requestIP" field.
func RequestIPHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldRequestIP, v))
}

// RequestIPIsNil applies the IsNil predicate on the "requestIP" field.
func RequestIPIsNil() predicate.Record {
	return predicate.Record(sql.FieldIsNull(FieldRequestIP))
}

// RequestIPNotNil applies the NotNil predicate on the "requestIP" field.
func RequestIPNotNil() predicate.Record {
	return predicate.Record(sql.FieldNotNull(FieldRequestIP))
}

// RequestIPEqualFold applies the EqualFold predicate on the "requestIP" field.
func RequestIPEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldRequestIP, v))
}

// RequestIPContainsFold applies the ContainsFold predicate on the "requestIP" field.
func RequestIPContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldRequestIP, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Record {
	return predicate.Record(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Record {
	return predicate.Record(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldDescription, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Record) predicate.Record {
	return predicate.Record(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Record) predicate.Record {
	return predicate.Record(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Record) predicate.Record {
	return predicate.Record(func(s *sql.Selector) {
		p(s.Not())
	})
}
