// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"netinfo/ent/predicate"
	"netinfo/ent/record"
	"netinfo/ent/schema"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// RecordUpdate is the builder for updating Record entities.
type RecordUpdate struct {
	config
	hooks    []Hook
	mutation *RecordMutation
}

// Where appends a list predicates to the RecordUpdate builder.
func (ru *RecordUpdate) Where(ps ...predicate.Record) *RecordUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetUpdatedAt sets the "updatedAt" field.
func (ru *RecordUpdate) SetUpdatedAt(t time.Time) *RecordUpdate {
	ru.mutation.SetUpdatedAt(t)
	return ru
}

// SetRequestIP sets the "requestIP" field.
func (ru *RecordUpdate) SetRequestIP(s string) *RecordUpdate {
	ru.mutation.SetRequestIP(s)
	return ru
}

// SetNillableRequestIP sets the "requestIP" field if the given value is not nil.
func (ru *RecordUpdate) SetNillableRequestIP(s *string) *RecordUpdate {
	if s != nil {
		ru.SetRequestIP(*s)
	}
	return ru
}

// ClearRequestIP clears the value of the "requestIP" field.
func (ru *RecordUpdate) ClearRequestIP() *RecordUpdate {
	ru.mutation.ClearRequestIP()
	return ru
}

// SetDescription sets the "description" field.
func (ru *RecordUpdate) SetDescription(s string) *RecordUpdate {
	ru.mutation.SetDescription(s)
	return ru
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ru *RecordUpdate) SetNillableDescription(s *string) *RecordUpdate {
	if s != nil {
		ru.SetDescription(*s)
	}
	return ru
}

// ClearDescription clears the value of the "description" field.
func (ru *RecordUpdate) ClearDescription() *RecordUpdate {
	ru.mutation.ClearDescription()
	return ru
}

// SetNetInterfaces sets the "netInterfaces" field.
func (ru *RecordUpdate) SetNetInterfaces(si []schema.NetInterface) *RecordUpdate {
	ru.mutation.SetNetInterfaces(si)
	return ru
}

// AppendNetInterfaces appends si to the "netInterfaces" field.
func (ru *RecordUpdate) AppendNetInterfaces(si []schema.NetInterface) *RecordUpdate {
	ru.mutation.AppendNetInterfaces(si)
	return ru
}

// Mutation returns the RecordMutation object of the builder.
func (ru *RecordUpdate) Mutation() *RecordMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RecordUpdate) Save(ctx context.Context) (int, error) {
	ru.defaults()
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RecordUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RecordUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RecordUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ru *RecordUpdate) defaults() {
	if _, ok := ru.mutation.UpdatedAt(); !ok {
		v := record.UpdateDefaultUpdatedAt()
		ru.mutation.SetUpdatedAt(v)
	}
}

func (ru *RecordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(record.Table, record.Columns, sqlgraph.NewFieldSpec(record.FieldID, field.TypeString))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.UpdatedAt(); ok {
		_spec.SetField(record.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ru.mutation.RequestIP(); ok {
		_spec.SetField(record.FieldRequestIP, field.TypeString, value)
	}
	if ru.mutation.RequestIPCleared() {
		_spec.ClearField(record.FieldRequestIP, field.TypeString)
	}
	if value, ok := ru.mutation.Description(); ok {
		_spec.SetField(record.FieldDescription, field.TypeString, value)
	}
	if ru.mutation.DescriptionCleared() {
		_spec.ClearField(record.FieldDescription, field.TypeString)
	}
	if value, ok := ru.mutation.NetInterfaces(); ok {
		_spec.SetField(record.FieldNetInterfaces, field.TypeJSON, value)
	}
	if value, ok := ru.mutation.AppendedNetInterfaces(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, record.FieldNetInterfaces, value)
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{record.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RecordUpdateOne is the builder for updating a single Record entity.
type RecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecordMutation
}

// SetUpdatedAt sets the "updatedAt" field.
func (ruo *RecordUpdateOne) SetUpdatedAt(t time.Time) *RecordUpdateOne {
	ruo.mutation.SetUpdatedAt(t)
	return ruo
}

// SetRequestIP sets the "requestIP" field.
func (ruo *RecordUpdateOne) SetRequestIP(s string) *RecordUpdateOne {
	ruo.mutation.SetRequestIP(s)
	return ruo
}

// SetNillableRequestIP sets the "requestIP" field if the given value is not nil.
func (ruo *RecordUpdateOne) SetNillableRequestIP(s *string) *RecordUpdateOne {
	if s != nil {
		ruo.SetRequestIP(*s)
	}
	return ruo
}

// ClearRequestIP clears the value of the "requestIP" field.
func (ruo *RecordUpdateOne) ClearRequestIP() *RecordUpdateOne {
	ruo.mutation.ClearRequestIP()
	return ruo
}

// SetDescription sets the "description" field.
func (ruo *RecordUpdateOne) SetDescription(s string) *RecordUpdateOne {
	ruo.mutation.SetDescription(s)
	return ruo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ruo *RecordUpdateOne) SetNillableDescription(s *string) *RecordUpdateOne {
	if s != nil {
		ruo.SetDescription(*s)
	}
	return ruo
}

// ClearDescription clears the value of the "description" field.
func (ruo *RecordUpdateOne) ClearDescription() *RecordUpdateOne {
	ruo.mutation.ClearDescription()
	return ruo
}

// SetNetInterfaces sets the "netInterfaces" field.
func (ruo *RecordUpdateOne) SetNetInterfaces(si []schema.NetInterface) *RecordUpdateOne {
	ruo.mutation.SetNetInterfaces(si)
	return ruo
}

// AppendNetInterfaces appends si to the "netInterfaces" field.
func (ruo *RecordUpdateOne) AppendNetInterfaces(si []schema.NetInterface) *RecordUpdateOne {
	ruo.mutation.AppendNetInterfaces(si)
	return ruo
}

// Mutation returns the RecordMutation object of the builder.
func (ruo *RecordUpdateOne) Mutation() *RecordMutation {
	return ruo.mutation
}

// Where appends a list predicates to the RecordUpdate builder.
func (ruo *RecordUpdateOne) Where(ps ...predicate.Record) *RecordUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RecordUpdateOne) Select(field string, fields ...string) *RecordUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Record entity.
func (ruo *RecordUpdateOne) Save(ctx context.Context) (*Record, error) {
	ruo.defaults()
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RecordUpdateOne) SaveX(ctx context.Context) *Record {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RecordUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RecordUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ruo *RecordUpdateOne) defaults() {
	if _, ok := ruo.mutation.UpdatedAt(); !ok {
		v := record.UpdateDefaultUpdatedAt()
		ruo.mutation.SetUpdatedAt(v)
	}
}

func (ruo *RecordUpdateOne) sqlSave(ctx context.Context) (_node *Record, err error) {
	_spec := sqlgraph.NewUpdateSpec(record.Table, record.Columns, sqlgraph.NewFieldSpec(record.FieldID, field.TypeString))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Record.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, record.FieldID)
		for _, f := range fields {
			if !record.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != record.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.UpdatedAt(); ok {
		_spec.SetField(record.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ruo.mutation.RequestIP(); ok {
		_spec.SetField(record.FieldRequestIP, field.TypeString, value)
	}
	if ruo.mutation.RequestIPCleared() {
		_spec.ClearField(record.FieldRequestIP, field.TypeString)
	}
	if value, ok := ruo.mutation.Description(); ok {
		_spec.SetField(record.FieldDescription, field.TypeString, value)
	}
	if ruo.mutation.DescriptionCleared() {
		_spec.ClearField(record.FieldDescription, field.TypeString)
	}
	if value, ok := ruo.mutation.NetInterfaces(); ok {
		_spec.SetField(record.FieldNetInterfaces, field.TypeJSON, value)
	}
	if value, ok := ruo.mutation.AppendedNetInterfaces(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, record.FieldNetInterfaces, value)
		})
	}
	_node = &Record{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{record.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
